name: sima_portal
description: A new Flutter project.

# ///7682

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

  # لوگوی اصلی
  # لوگوی ناتیفیکیشن
  # اسم اصلی

  #flutter pub run flutter_launcher_icons:main
  #flutter build apk --target-platform=android-arm --no-sound-null-safety
  #flutter run -d chrome
#flutter build apk --release

version: 2.0.5+25

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  http: ^0.13.4
#  jalali_calendar: ^1.0.4
  font_awesome_flutter: ^10.1.0
#  curved_navigation_bar: ^1.0.1
  dio: ^4.0.4
  textfield_search: ^0.8.0
  flutter_custom_clippers: ^2.0.0
  connectivity: ^3.0.6
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.9
  searchable_dropdown: ^1.1.3
#  image_picker_platform_interface: ^2.0.0
  date_format: ^2.0.4
  firebase_messaging: ^11.1.0
  firebase_core: ^1.13.1
  path_provider: ^2.0.7
#  flutter_svg: ^0.20.0-nullsafety.3
  flutter_svg: ^0.23.0+1
  cached_network_image: ^3.1.0+1
  accordion: ^2.0.1
  flutter_icons: ^1.1.0
  pie_chart: ^5.0.1
  persian_date: ^0.1.5
  persian_number_utility: ^1.1.1
  barcode_scan2: ^4.2.0
  image_cropper: ^1.4.1
  rflutter_alert: ^2.0.4
  flutter_question_answer_widget: ^0.0.2
  introduction_screen: ^3.0.2
  cool_alert: ^1.1.0
  flutter_local_notifications: ^9.6.1
  #  flutter_background_service: ^2.0.0
  jalali_table_calendar: ^1.0.2
  avatar_glow: ^2.0.2
  video_player: ^2.4.2
  chewie: ^1.3.2
  fluttertoast: ^8.0.9
  mask_text_input_formatter: ^2.3.0
  home_widget: ^0.1.6
  workmanager: ^0.5.0
  flutter_animator: ^3.2.2
#  local_auth: ^2.1.0
  fl_chart: ^0.55.0
  flutter_spinkit: ^5.1.0
  percent_indicator: ^4.2.2
  carousel_slider: ^4.1.1
  bottom_navy_bar: ^6.0.0
  url_launcher: ^6.1.4
  animated_snack_bar: ^0.2.2
  syncfusion_flutter_datagrid_export: ^20.2.40-beta
  syncfusion_flutter_xlsio: ^20.2.40-beta
  open_file: ^3.2.1
  path_provider_platform_interface: ^2.0.4
  flutter_smart_dialog: ^4.5.3+6
  custom_pop_up_menu: ^1.2.4
  just_audio: ^0.9.30
  shimmer: ^2.0.0
#  flutter_html: ^2.2.1
#  shamsi_date: ^1.0.1

  flutter_staggered_animations: ^1.0.0
  bordered_text: ^2.0.0
  device_info_plus: ^4.0.0
#  photo_view: ^0.14.0
#  device_info_plus_windows: ^4.0.0
#  ffi: ^1.0.0


  #  downloads_path_provider_28: ^0.1.2
#  permission_handler: ^8.3.0
#  audioplayers: ^0.20.1
#  flowder: ^0.2.0

  #floating_action_bubble: ^1.1.4
  #nice_buttons: ^0.0.2
  #fluent_appbar: ^2.0.0
  #flutter_intro: ^3.0.2
  #flutter_siri_suggestions: ^2.1.0
  #fab_circular_menu: ^0.1.0
  #clear_all_notifications: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8

  flutter_lints: ^2.0.0



flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/appbar_logo.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/appbar_logo.png
    - assets/images/appbar_logo_sima.png
    - assets/images/appbar_logo_novin.png
    - assets/images/appbar_logo_baya.png
    - assets/images/arrow1.svg
    - assets/images/bc.jpg
    - assets/images/profile_bc.jpg
    - assets/images/q.jpg
    - assets/images/bag.png
    - assets/images/tosan.png
    - assets/images/sup.jpg
    - assets/images/nomoney.jpg
    - assets/images/Markazi.jpg
    - assets/images/MaliyatLogo.jpg
    - assets/images/transfer.jpg
    - assets/images/devices.jpg
    - assets/images/pazirande.png
    - assets/images/upload.png
    - assets/images/takhsis.png
    - assets/images/device.png
    - assets/images/hesab.png
    - assets/images/register.png
    - assets/images/replace.png
    - assets/images/riz.png
    - assets/images/support.png
    - assets/images/learning.png
    - assets/images/moaref.png
    - assets/images/iranflag.png
    - assets/images/taqalob.png
    - assets/images/Logo_Sima_Cart.gif
    - assets/images/person.png
    - assets/images/empty.png
    - assets/images/pos1.png
    - assets/images/pos2.png
    - assets/images/pos3.png
    - assets/images/pasargad.png
    - assets/images/irankish.png
    - assets/images/sadad.png
    - assets/images/sadad2.png
    - assets/images/behpardakht.png
    - assets/images/novin.png
    - assets/images/sepehr.png
    - assets/images/Terminal.png
    - assets/images/Mahsolat.png
    - assets/images/reqterminal.png
    - assets/images/eslah.png
    - assets/images/shop.png
    - assets/images/target.png
    - assets/images/info.png
    - assets/images/xlsx.png
    - assets/images/pdf.png
    - assets/images/download.png
    - assets/images/estelam.png
    - assets/ding1.mp3
    - assets/ding2.mp3

  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/sans.ttf
          weight: 500
        - asset: assets/fonts/sans-bold.ttf
          weight: 800
        - asset: assets/fonts/sans-light.ttf
          weight: 300